spring:
  application:
    name: FamilyDiscovery
  main:
    web-application-type: servlet

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://familydiscovery.onrender.com/eureka/ # Change localhost to your public URL
  server:
    enable-self-preservation: false
  instance:
    hostname: familydiscovery.onrender.com # Ensure correct indentation here
    prefer-ip-address: true
