networks:
  familygram-network:
    driver: bridge

services:
  familyauth:
    build: 
      context: .
      dockerfile: familyauth/Dockerfile
    container_name: familyauth
    ports:
      - "8081:8080"
    env_file: .env
    networks:
      - familygram-network

  familyfeed:
    build: 
      context: .
      dockerfile: familyfeed/Dockerfile
    container_name: familyfeed
    ports:
      - "8084:8080"
    env_file: .env
    depends_on:
      - kafka
    networks:
      - familygram-network

  familypost:
    build: 
      context: .
      dockerfile: familypost/Dockerfile
    container_name: familypost
    ports:
      - "8083:8080"
    env_file: .env
    depends_on:
      - kafka
    networks:
      - familygram-network

  familynotification:
    build: 
      context: .
      dockerfile: familynotification/Dockerfile
    container_name: familynotification
    ports:
      - "8085:8080"
    env_file: .env
    depends_on:
      - kafka
    networks:
      - familygram-network

  services:
    kafka:
      image: apache/kafka:4.0.0
      container_name: kafka
      restart: always
      ports:
        - "9092:9092"
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: "broker,controller"
        KAFKA_LISTENERS: "PLAINTEXT://:9092"
        KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
        KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
        KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
        KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      networks:
        - familygram-network

