spring:
  application:
    name: FamilyChat
  jackson:
    time-zone: UTC
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}

feign:
  client-url: ${AUTH_URL}

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: ${MicroZone}
