spring:
  application:
    name: FamilyFeed
  data:
    mongodb:
      uri: ${BlogDBUrl}
      database: ${BlogDBName}
  servlet:
    multipart:
      enabled: ${MULTIPART_ENABLED}
      max-file-size: ${MAX_UPLOAD_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  main:
    allow-circular-references: true
  devtools:
    add-properties: false
  jackson:
    time-zone: UTC
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC

jwt:
  secret: ${JWT_SECRET}
  tokenValidityInMilliSeconds: ${JWT_TOKEN_VALIDITY_IN_MILLISECONDS}
  tokenRefreshInMilliSeconds: ${JWT_TOKEN_REFRESH_IN_MILLISECONDS}

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
