spring:
  application:
    name: FamilyFeed
  data:
    mongodb:
      uri: ${DBURL}
      database: ${DBNAME}
  servlet:
    multipart:
      enabled: ${MULTIPART_ENABLED}
      max-file-size: ${MAX_UPLOAD_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  main:
    allow-circular-references: true
  devtools:
    add-properties: false
  jackson:
    time-zone: UTC
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  tokenValidityInMilliSeconds: ${JWT_TOKEN_VALIDITY_IN_MILLISECONDS}
  tokenRefreshInMilliSeconds: ${JWT_TOKEN_REFRESH_IN_MILLISECONDS}

feign:
  client-url: ${AUTH_URL}

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: ${MicroZone}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
