server:
  port: 8085

spring:
  application:
    name: FamilyNotificaton
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: ${DBURL}
      database: ${DBNAME}
  jackson:
    time-zone: UTC
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: ${BROKER_URL}
    consumer:
      auto-offset-reset: latest
    listener:
      ack-mode: manual

eureka:
  client:
    serviceUrl:
      defaultZone: ${MicroZone}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
