server:
  port: 8085

spring:
  application:
    name: FamilyNotificaton
  data:
    mongodb:
      uri: ${DBURL}
      database: ${DBNAME}
  jackson:
    time-zone: UTC
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC

  kafka:
    bootstrap-servers: broker:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: latest
    listener:
      ack-mode: manual

# Auth:
#   Cors:
#     Url: ${CORS_URL}
#     Methods: ${CORS_METHODS}

# logging:
#   level:
#     web: OFF
#     org.springframework.web: ERROR
#     feign: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
